export const buttonColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const buttonContent = [
  {
    id: 1,
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Content to render inside the button",
  },
  {
    id: 2,
    key: "className",
    prop: "className",
    type: "string",
    default: "undefined",
    description: "Additional CSS classes to apply",
  },
  {
    id: 3,
    key: "ariaLabel",
    prop: "ariaLabel",
    type: "string",
    default: "undefined",
    description: "Accessibility label for screen readers",
  },
  {
    id: 4,
    key: "color",
    prop: "color",
    type: "ButtonColor",
    default: "'default'",
    description: "Color theme: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger'",
  },
  {
    id: 5,
    key: "disabled",
    prop: "disabled",
    type: "boolean",
    default: "false",
    description: "Whether the button is disabled",
  },
  {
    id: 6,
    key: "isLoading",
    prop: "isLoading",
    type: "boolean",
    default: "false",
    description: "Whether the button is in loading state",
  },
  {
    id: 7,
    key: "onClick",
    prop: "onClick",
    type: "() => void",
    default: "undefined",
    description: "Click handler function",
  },
  {
    id: 8,
    key: "type",
    prop: "type",
    type: "'button' | 'submit' | 'reset'",
    default: "'button'",
    description: "HTML button type attribute",
  },
  {
    id: 9,
    key: "size",
    prop: "size",
    type: "ButtonSize",
    default: "'md'",
    description: "Size variant: 'xs' | 'sm' | 'md' | 'lg' | 'xl'",
  },
  {
    id: 10,
    key: "variant",
    prop: "variant",
    type: "ButtonVariant",
    default: "'solid'",
    description: "Visual style: 'solid' | 'outline' | 'ghost' | 'link' | 'gradient'",
  },
  {
    id: 11,
    key: "radius",
    prop: "radius",
    type: "ButtonRadius",
    default: "'md'",
    description: "Border radius: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full'",
  },
  {
    id: 12,
    key: "startIcon",
    prop: "startIcon",
    type: "ReactNode",
    default: "undefined",
    description: "Icon to display before text",
  },
  {
    id: 13,
    key: "endIcon",
    prop: "endIcon",
    type: "ReactNode",
    default: "undefined",
    description: "Icon to display after text",
  },
  {
    id: 14,
    key: "fullWidth",
    prop: "fullWidth",
    type: "boolean",
    default: "false",
    description: "Whether to show full width",
  },
  {
    id: 15,
    key: "disableAnimation",
    prop: "disableAnimation",
    type: "boolean",
    default: "false",
    description: "Whether to disable hover and focus animations",
  },
  {
    id: 16,
    key: "hoverAnimation",
    prop: "hoverAnimation",
    type: "ButtonHoverAnimation",
    default: "'scale'",
    description: "Hover animation: 'none' | 'scale' | 'lift' | 'bounce' | 'pulse' | 'shake' | 'rotate' | 'glow'",
  },
  {
    id: 17,
    key: "clickAnimation",
    prop: "clickAnimation",
    type: "ButtonClickAnimation",
    default: "'scale'",
    description: "Click animation: 'none' | 'scale' | 'bounce' | 'ripple' | 'press' | 'punch' | 'wiggle'",
  },
  {
    id: 18,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "undefined",
    description: "Test ID for testing frameworks",
  },
];

export const buttonGroupColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const buttonGroupContent = [
  {
    id: 1,
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Button components to render inside the group",
  },
  {
    id: 2,
    key: "className",
    prop: "className",
    type: "string",
    default: "undefined",
    description: "Additional CSS classes to apply",
  },
  {
    id: 3,
    key: "size",
    prop: "size",
    type: "ButtonSize",
    default: "'md'",
    description: "Size variant for all buttons in group",
  },
  {
    id: 4,
    key: "color",
    prop: "color",
    type: "ButtonColor",
    default: "'default'",
    description: "Color theme for all buttons in group",
  },
  {
    id: 5,
    key: "variant",
    prop: "variant",
    type: "ButtonVariant",
    default: "'solid'",
    description: "Visual style variant for all buttons in group",
  },
  {
    id: 6,
    key: "radius",
    prop: "radius",
    type: "ButtonRadius",
    default: "'md'",
    description: "Border radius for all buttons in group",
  },
  {
    id: 7,
    key: "isAttached",
    prop: "isAttached",
    type: "boolean",
    default: "false",
    description: "Whether buttons are attached (no spacing)",
  },
  {
    id: 8,
    key: "disabled",
    prop: "disabled",
    type: "boolean",
    default: "false",
    description: "Whether the group is disabled",
  },
  {
    id: 9,
    key: "disableAnimation",
    prop: "disableAnimation",
    type: "boolean",
    default: "false",
    description: "Whether to disable hover and focus animations for all buttons",
  },
  {
    id: 10,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "undefined",
    description: "Test ID for testing frameworks",
  },
];