// Checkbox component props table
export const checkboxColumns = [
  { key: "prop", label: "Prop", allowsSorting: false },
  { key: "type", label: "Type", allowsSorting: false },
  { key: "default", label: "Default", allowsSorting: false },
  { key: "description", label: "Description", allowsSorting: false },
];

export const checkboxContent = [
  {
    id: "1",
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Content to render as checkbox label",
  },
  {
    id: "2",
    key: "icon",
    prop: "icon",
    type: "React.ComponentType<CheckboxIconProps>",
    default: "-",
    description: "Custom icon component to replace default checkmark",
  },
  {
    id: "3",
    key: "value",
    prop: "value",
    type: "string",
    default: "-",
    description: "Value attribute for the checkbox input",
  },
  {
    id: "4",
    key: "name",
    prop: "name",
    type: "string",
    default: "-",
    description: "Name attribute for the checkbox input",
  },
  {
    id: "5",
    key: "size",
    prop: "size",
    type: "'sm' | 'md' | 'lg'",
    default: "'md'",
    description: "Size variant of the checkbox",
  },
  {
    id: "6",
    key: "color",
    prop: "color",
    type: "'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger'",
    default: "'default'",
    description: "Color theme of the checkbox",
  },
  {
    id: "7",
    key: "radius",
    prop: "radius",
    type: "'none' | 'sm' | 'md' | 'lg' | 'full'",
    default: "'md'",
    description: "Border radius of the checkbox",
  },
  {
    id: "8",
    key: "lineThrough",
    prop: "lineThrough",
    type: "boolean",
    default: "false",
    description: "Show line-through effect on label when checked",
  },
  {
    id: "9",
    key: "isSelected",
    prop: "isSelected",
    type: "boolean",
    default: "-",
    description: "Whether the checkbox is selected (controlled)",
  },
  {
    id: "10",
    key: "defaultSelected",
    prop: "defaultSelected",
    type: "boolean",
    default: "false",
    description: "Default selected state (uncontrolled)",
  },
  {
    id: "11",
    key: "isRequired",
    prop: "isRequired",
    type: "boolean",
    default: "false",
    description: "Whether the checkbox is required",
  },
  {
    id: "12",
    key: "isReadOnly",
    prop: "isReadOnly",
    type: "boolean",
    default: "false",
    description: "Whether the checkbox is read-only",
  },
  {
    id: "13",
    key: "isDisabled",
    prop: "isDisabled",
    type: "boolean",
    default: "false",
    description: "Whether the checkbox is disabled",
  },
  {
    id: "14",
    key: "isIndeterminate",
    prop: "isIndeterminate",
    type: "boolean",
    default: "false",
    description: "Whether the checkbox is in indeterminate state",
  },
  {
    id: "15",
    key: "isInvalid",
    prop: "isInvalid",
    type: "boolean",
    default: "false",
    description: "Whether the checkbox is invalid",
  },
  {
    id: "16",
    key: "validationState",
    prop: "validationState",
    type: "'valid' | 'invalid'",
    default: "-",
    description: "Validation state of the checkbox",
  },
  {
    id: "17",
    key: "disableAnimation",
    prop: "disableAnimation",
    type: "boolean",
    default: "false",
    description: "Whether to disable hover and focus animations",
  },
  {
    id: "18",
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes to apply",
  },
  {
    id: "19",
    key: "classNames",
    prop: "classNames",
    type: "Record<'base' | 'wrapper' | 'icon' | 'label' | 'hiddenInput', string>",
    default: "-",
    description: "Custom class names for different component slots",
  },
  {
    id: "20",
    key: "onChange",
    prop: "onChange",
    type: "(event: ChangeEvent) => void",
    default: "-",
    description: "Native change event handler",
  },
  {
    id: "21",
    key: "onValueChange",
    prop: "onValueChange",
    type: "(isSelected: boolean) => void",
    default: "-",
    description: "Value change event handler",
  },
  {
    id: "22",
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test ID for testing frameworks",
  },
];

// Type definitions for Checkbox
export const checkboxTypeDefinitions = [
  {
    id: "1",
    name: "CheckboxSize",
    value: "\"sm\" | \"md\" | \"lg\"",
  },
  {
    id: "2",
    name: "CheckboxColor",
    value:
      "\"default\" | \"primary\" | \"secondary\" | \"success\" | \"warning\" | \"danger\"",
  },
  {
    id: "3",
    name: "CheckboxRadius",
    value: "\"none\" | \"sm\" | \"md\" | \"lg\" | \"full\"",
  },
  {
    id: "4",
    name: "CheckboxValidationState",
    value: "\"valid\" | \"invalid\"",
  },
];
