// ImageProps columns and content
export const imagePropsColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const imagePropsContent = [
  {
    id: 1,
    key: "src",
    prop: "src",
    type: "string",
    default: "-",
    description: "Image source URL (required)",
  },
  {
    id: 2,
    key: "srcSet",
    prop: "srcSet",
    type: "string",
    default: "-",
    description: "Image source set for responsive images",
  },
  {
    id: 3,
    key: "sizes",
    prop: "sizes",
    type: "string",
    default: "-",
    description: "Image sizes attribute for responsive images",
  },
  {
    id: 4,
    key: "alt",
    prop: "alt",
    type: "string",
    default: "-",
    description: "Alternative text for the image (required)",
  },
  {
    id: 5,
    key: "width",
    prop: "width",
    type: "number",
    default: "-",
    description: "Image width in pixels",
  },
  {
    id: 6,
    key: "height",
    prop: "height",
    type: "number",
    default: "-",
    description: "Image height in pixels",
  },
  {
    id: 7,
    key: "radius",
    prop: "radius",
    type: '"none" | "sm" | "md" | "lg" | "full"',
    default: '"md"',
    description: "Border radius variant",
  },
  {
    id: 8,
    key: "shadow",
    prop: "shadow",
    type: '"none" | "sm" | "md" | "lg"',
    default: '"none"',
    description: "Shadow variant",
  },
  {
    id: 9,
    key: "loading",
    prop: "loading",
    type: '"eager" | "lazy"',
    default: '"lazy"',
    description: "Loading behavior",
  },
  {
    id: 10,
    key: "fallbackSrc",
    prop: "fallbackSrc",
    type: "string",
    default: "-",
    description: "Fallback image source URL when main image fails to load",
  },
  {
    id: 11,
    key: "isBlurred",
    prop: "isBlurred",
    type: "boolean",
    default: "false",
    description: "Whether to apply blur effect",
  },
  {
    id: 12,
    key: "isZoomed",
    prop: "isZoomed",
    type: "boolean",
    default: "false",
    description: "Whether to enable zoom on hover",
  },
  {
    id: 13,
    key: "removeWrapper",
    prop: "removeWrapper",
    type: "boolean",
    default: "false",
    description: "Whether to remove the wrapper div",
  },
  {
    id: 14,
    key: "disableSkeleton",
    prop: "disableSkeleton",
    type: "boolean",
    default: "false",
    description: "Whether to disable skeleton loading animation",
  },
  {
    id: 15,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes to apply",
  },
  {
    id: 16,
    key: "classNames",
    prop: "classNames",
    type: 'Record<"img" | "wrapper" | "zoomedWrapper" | "blurredImg", string>',
    default: "-",
    description: "Custom class names for different component slots",
  },
  {
    id: 17,
    key: "onLoad",
    prop: "onLoad",
    type: "ReactEventHandler<HTMLImageElement>",
    default: "-",
    description: "Image load event handler",
  },
  {
    id: 18,
    key: "onError",
    prop: "onError",
    type: "() => void",
    default: "-",
    description: "Image error event handler",
  },
  {
    id: 19,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test ID for testing frameworks",
  },
];
