export const inputColumns = [
  { key: "prop", label: "Prop", allowsSorting: false },
  { key: "type", label: "Type", allowsSorting: false },
  { key: "default", label: "Default", allowsSorting: false },
  { key: "description", label: "Description", allowsSorting: false },
];

export const inputContent = [
  // Content Props
  {
    id: 1,
    key: "label",
    prop: "label",
    type: "ReactNode",
    default: "-",
    description: "Input label text or element",
  },
  {
    id: 2,
    key: "placeholder",
    prop: "placeholder",
    type: "string",
    default: "-",
    description: "Input placeholder text",
  },
  {
    id: 3,
    key: "description",
    prop: "description",
    type: "ReactNode",
    default: "-",
    description: "Helper text displayed below the input",
  },
  {
    id: 4,
    key: "errorMessage",
    prop: "errorMessage",
    type: "ReactNode | ((validation) => ReactNode)",
    default: "-",
    description: "Error message - can be static or function",
  },
  {
    id: 5,
    key: "startContent",
    prop: "startContent",
    type: "ReactNode",
    default: "-",
    description: "Content to display at the start of the input",
  },
  {
    id: 6,
    key: "endContent",
    prop: "endContent",
    type: "ReactNode",
    default: "-",
    description: "Content to display at the end of the input",
  },

  // Value & Control
  {
    id: 7,
    key: "value",
    prop: "value",
    type: "string",
    default: "-",
    description: "Controlled input value",
  },
  {
    id: 8,
    key: "defaultValue",
    prop: "defaultValue",
    type: "string",
    default: "-",
    description: "Default value for uncontrolled input",
  },

  // Visual Properties
  {
    id: 9,
    key: "variant",
    prop: "variant",
    type: "'flat' | 'bordered' | 'faded' | 'underlined'",
    default: "'flat'",
    description: "Visual variant of the input",
  },
  {
    id: 10,
    key: "color",
    prop: "color",
    type: "'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger'",
    default: "'default'",
    description: "Color theme of the input",
  },
  {
    id: 11,
    key: "size",
    prop: "size",
    type: "'sm' | 'md' | 'lg'",
    default: "'md'",
    description: "Size variant of the input",
  },
  {
    id: 12,
    key: "radius",
    prop: "radius",
    type: "'none' | 'sm' | 'md' | 'lg' | 'full'",
    default: "'md'",
    description: "Border radius of the input",
  },
  {
    id: 13,
    key: "labelPlacement",
    prop: "labelPlacement",
    type: "'inside' | 'outside' | 'outside-left'",
    default: "'inside'",
    description: "Position of the label relative to the input",
  },
  {
    id: 14,
    key: "fullWidth",
    prop: "fullWidth",
    type: "boolean",
    default: "true",
    description: "Whether input takes full width of its container",
  },

  // Input Properties
  {
    id: 15,
    key: "type",
    prop: "type",
    type: "'text' | 'email' | 'url' | 'password' | 'tel' | 'search' | 'file' | 'number'",
    default: "'text'",
    description: "HTML input type",
  },
  {
    id: 16,
    key: "minLength",
    prop: "minLength",
    type: "number",
    default: "-",
    description: "Minimum length validation",
  },
  {
    id: 17,
    key: "maxLength",
    prop: "maxLength",
    type: "number",
    default: "-",
    description: "Maximum length validation",
  },
  {
    id: 18,
    key: "pattern",
    prop: "pattern",
    type: "string",
    default: "-",
    description: "Regular expression pattern for validation",
  },

  // State Properties
  {
    id: 19,
    key: "isRequired",
    prop: "isRequired",
    type: "boolean",
    default: "false",
    description: "Whether the input is required",
  },
  {
    id: 20,
    key: "isDisabled",
    prop: "isDisabled",
    type: "boolean",
    default: "false",
    description: "Whether the input is disabled",
  },
  {
    id: 21,
    key: "isReadOnly",
    prop: "isReadOnly",
    type: "boolean",
    default: "false",
    description: "Whether the input is read-only",
  },
  {
    id: 22,
    key: "isInvalid",
    prop: "isInvalid",
    type: "boolean",
    default: "false",
    description: "Whether the input has validation errors",
  },
  {
    id: 23,
    key: "isClearable",
    prop: "isClearable",
    type: "boolean",
    default: "false",
    description: "Whether to show clear button when input has value",
  },

  // Animation & Styling
  {
    id: 24,
    key: "disableAnimation",
    prop: "disableAnimation",
    type: "boolean",
    default: "false",
    description: "Whether to disable animations",
  },
  {
    id: 25,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes to apply",
  },
  {
    id: 26,
    key: "classNames",
    prop: "classNames",
    type: "InputClassNames",
    default: "-",
    description: "Custom class names for different component parts",
  },

  // Validation
  {
    id: 27,
    key: "validate",
    prop: "validate",
    type: "(value: string) => ValidationError | true | null",
    default: "-",
    description: "Custom validation function",
  },
  {
    id: 28,
    key: "validationBehavior",
    prop: "validationBehavior",
    type: "'native' | 'aria'",
    default: "'native'",
    description: "How validation errors are presented",
  },

  // Events
  {
    id: 29,
    key: "onChange",
    prop: "onChange",
    type: "(event: ChangeEvent) => void",
    default: "-",
    description: "Native change event handler",
  },
  {
    id: 30,
    key: "onValueChange",
    prop: "onValueChange",
    type: "(value: string) => void",
    default: "-",
    description: "Value change handler (HeroUI style)",
  },
  {
    id: 31,
    key: "onClear",
    prop: "onClear",
    type: "() => void",
    default: "-",
    description: "Clear button click handler",
  },

  // Accessibility
  {
    id: 32,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test ID for automated testing",
  },
  {
    id: 33,
    key: "aria-label",
    prop: "aria-label",
    type: "string",
    default: "-",
    description: "ARIA label for accessibility",
  },
];
