export const switchPropsColumns = [
  { key: "prop", label: "Prop", allowsSorting: false },
  { key: "type", label: "Type", allowsSorting: false },
  { key: "default", label: "Default", allowsSorting: false },
  { key: "description", label: "Description", allowsSorting: false },
];

export const switchSlotsColumns = [
  { key: "slot", label: "Slot", allowsSorting: false },
  { key: "targetElement", label: "Target Element", allowsSorting: false },
];

export const switchContent = [
  // Content Props
  {
    id: 1,
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Content to render inside the button",
  },
  {
    id: 2,
    key: "className",
    prop: "className",
    type: "string",
    default: "undefined",
    description: "Additional CSS classes to apply",
  },
  {
    id: 3,
    key: "name",
    prop: "name",
    type: "string",
    default: "undefined",
    description: "Name attribute for the switch input",
  },
  {
    id: 4,
    key: "size",
    prop: "size",
    type: "sm | md | lg",
    default: "md",
    description: "Size variant of the switch",
  },
  {
    id: 5,
    key: "color",
    prop: "color",
    type: "default | primary | secondary | success | warning | danger",
    default: "primary",
    description: "Color theme of the switch",
  },
  {
    id: 6,
    key: "thumbIcon",
    prop: "thumbIcon",
    type: "React.ComponentType<ThumbIconProps>",
    default: "-",
    description: "Custom icon component for the switch thumb",
  },
  {
    id: 7,
    key: "startContent",
    prop: "startContent",
    type: "ReactNode",
    default: "-",
    description: "Content to display at the start of the switch",
  },
  {
    id: 8,
    key: "endContent",
    prop: "endContent",
    type: "ReactNode",
    default: "-",
    description: "Content to display at the end of the switch",
  },
  {
    id: 9,
    key: "isSelected",
    prop: "isSelected",
    type: "boolean",
    default: "-",
    description: "Whether the switch is selected (controlled)",
  },
  {
    id: 10,
    key: "defaultSelected",
    prop: "defaultSelected",
    type: "boolean",
    default: "false",
    description: "Default selected state for (uncontrolled)",
  },
  {
    id: 11,
    key: "isReadOnly",
    prop: "isReadOnly",
    type: "boolean",
    default: "false",
    description: "Whether the switch is read-only",
  },
  {
    id: 12,
    key: "isDisabled",
    prop: "isDisabled",
    type: "boolean",
    default: "false",
    description: "Whether the switch is disabled",
  },
  {
    id: 13,
    key: "disableAnimation",
    prop: "disableAnimation",
    type: "boolean",
    default: "false",
    description: "Whether to disable switch animation",
  },
  {
    id: 14,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional Tailwind classes to apply",
  },
  {
    id: 15,
    key: "classNames",
    prop: "classNames",
    type: "SwitchSlots",
    default: "-",
    description: "Custom class names for different slots",
  },
  {
    id: 16,
    key: "onChange",
    prop: "onChange",
    type: "(event: ChangeEvent<HTMLInputElement>) => void",
    default: "-",
    description: "Native change event handler",
  },
  {
    id: 17,
    key: "onValueChange",
    prop: "onValueChange",
    type: "(isSelected: boolean) => void",
    default: "-",
    description: "Value change event handler",
  },
  {
    id: 18,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test ID for testing frameworks",
  },
];

export const thumbIconContent = [
  {
    id: 1,
    key: "isSelected",
    prop: "isSelected",
    default: "-",
    description: "Whether the switch is selected",
  },
  {
    id: 2,
    key: "className",
    prop: "className",
    default: "-",
    description: "Additional CSS classes to apply",
  },
];

export const switchSlotsContent = [
  { id: 1, slot: "base", targetElement: "Main swithc container" },
  { id: 2, slot: "wrapper", targetElement: "Switch track/background wrapper" },
  { id: 3, slot: "thumb", targetElement: "Switch thumb/handle element" },
  { id: 4, slot: "label", targetElement: "Switch label text" },
  {
    id: 5,
    slot: "startContent",
    targetElement: "Content displayed at start of switch",
  },
  {
    id: 6,
    slot: "endContent",
    targetElement: "Content displayed at end of switch",
  },
  { id: 7, slot: "thumbIcon", targetElement: "Custom icon within the thumb" },
  {
    id: 8,
    slot: "hiddenInput",
    targetElement: "Hidden input element for form integration",
  },
];
