export const columns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const customColorColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "example", label: "EXAMPLE", allowsSorting: false },
];
export const tableContent = [
  {
    id: 1,
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Table header and body components",
  },
  {
    id: 2,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes to apply",
  },
  {
    id: 3,
    key: "color",
    prop: "color",
    type: '"default" | "primary" | "secondary" | "success" | "warning" | "danger" | "custom"',
    default: '"default"',
    description:
      "Color theme of the table. Use 'custom' with customColor prop for personalized colors",
  },
  {
    id: 4,
    key: "customColor",
    prop: "customColor",
    type: "CustomTableColor",
    default: "-",
    description:
      "Custom color configuration object. Only used when color='custom'. Allows setting background, border, text, hover, selected colors, and gradients",
  },
  {
    id: 5,
    key: "layout",
    prop: "layout",
    type: '"auto" | "fixed"',
    default: '"auto"',
    description: "Table layout algorithm",
  },
  {
    id: 6,
    key: "radius",
    prop: "radius",
    type: '"none" | "sm" | "md" | "lg"',
    default: '"md"',
    description: "Border radius of the table",
  },
  {
    id: 7,
    key: "shadow",
    prop: "shadow",
    type: '"none" | "sm" | "md" | "lg"',
    default: '"none"',
    description: "Shadow variant",
  },
  {
    id: 8,
    key: "columns",
    prop: "columns",
    type: "columnDef[]",
    default: "-",
    description: "Column definitions for dynamic rendering",
  },
  {
    id: 9,
    key: "items",
    prop: "items",
    type: "Array[]",
    default: "-",
    description: "Data items for dynamic rendering",
  },
  {
    id: 10,
    key: "loading",
    prop: "loading",
    type: "boolean",
    default: "false",
    description: "Shows loading spinner when true",
  },
  {
    id: 11,
    key: "emptyContent",
    prop: "emptyContent",
    type: "ReactNode",
    default: "-",
    description: "Custom content to display when table is empty",
  },
  {
    id: 12,
    key: "selectionMode",
    prop: "selectionMode",
    type: '"none" | "single" | "multiple"',
    default: '"none"',
    description: "Selection mode for table rows",
  },
  {
    id: 13,
    key: "selectedKeys",
    prop: "selectedKeys",
    type: "Selection",
    default: "-",
    description: "Currently selected keys (controlled)",
  },
  {
    id: 14,
    key: "showSelectionCheckboxes",
    prop: "showSelectionCheckboxes",
    type: "boolean",
    default: "false",
    description: "Whether to show selection checkboxes",
  },
  {
    id: 15,
    key: "sortDescriptor",
    prop: "sortDescriptor",
    type: "SortDescriptor",
    default: "-",
    description: "Current sort configuration",
  },
  {
    id: 16,
    key: "isStriped",
    prop: "isStriped",
    type: "boolean",
    default: "false",
    description: "Whether to show alternating row colors",
  },
  {
    id: 17,
    key: "isCompact",
    prop: "isCompact",
    type: "boolean",
    default: "false",
    description: "Whether to use compact row spacing",
  },
  {
    id: 18,
    key: "isHeaderSticky",
    prop: "isHeaderSticky",
    type: "boolean",
    default: "false",
    description: "Whether to make header sticky on scroll",
  },
  {
    id: 19,
    key: "topContent",
    prop: "topContent",
    type: "ReactNode",
    default: "-",
    description: "Content render above the table",
  },
  {
    id: 20,
    key: "bottomContent",
    prop: "bottomContent",
    type: "ReactNode",
    default: "-",
    description: "Content rendered below the table",
  },
  {
    id: 21,
    key: "onSelectionChange",
    prop: "onSelectionChange",
    type: "(keys: Selection) => void",
    default: "-",
    description: "Selection change event handler",
  },
  {
    id: 22,
    key: "onSortChange",
    prop: "onSortChange",
    type: "(descriptor: SortDescriptor) => void",
    default: "-",
    description: "Sort change event handler",
  },
  {
    id: 23,
    key: "centerHeaderText",
    prop: "centerHeaderText",
    type: "boolean",
    default: "false",
    description:
      "Whether to center all column header text (overrides individual column align)",
  },
  {
    id: 24,
    key: "centerCellText",
    prop: "centerCellText",
    type: "boolean",
    default: "false",
    description:
      "Whether to center all table cell content (overrides individual column align)",
  },
  {
    id: 25,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test ID for testing frameworks",
  },
];

export const customColor = [
  {
    id: 1,
    prop: "background",
    type: "string",
    example: 'background: "bg-purple-50 dark:bg-purple-900/20"',
  },
  {
    key: 2,
    prop: "border",
    type: "string",
    example: 'border: "border-purple-200 dark:border-purple-800"',
  },
  {
    key: 3,
    prop: "text",
    type: "string",
    example: 'text: "text-purple-900 dark:text-purple-100"',
  },
  {
    key: 4,
    prop: "hover",
    type: "string",
    example: 'hover: "hover:bg-purple-100 dark:hover:bg-purple-900/30"',
  },
  {
    key: 5,
    prop: "selected",
    type: "string",
    example: 'selected: "bg-purple-200 dark:bg-purple-700/50"',
  },
  {
    key: 6,
    prop: "gradient",
    type: "string",
    example:
      "gradient: bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20",
  },
];
