// ToastProps columns and content
export const toastPropsColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const toastPropsContent = [
  {
    id: 1,
    key: "id",
    prop: "id",
    type: "string",
    default: "-",
    description: "Unique identifier for the toast",
  },
  {
    id: 2,
    key: "type",
    prop: "type",
    type: "ToastType",
    default: "default",
    description: "Toast type for styling and icon",
  },
  {
    id: 3,
    key: "title",
    prop: "title",
    type: "string",
    default: "-",
    description: "Optional title text for the toast",
  },
  {
    id: 4,
    key: "description",
    prop: "description",
    type: "string",
    default: "-",
    description: "Main message text for the toast",
  },
  {
    id: 5,
    key: "duration",
    prop: "duration",
    type: "number",
    default: "4000",
    description: "Auto-dismiss duration in milliseconds (0 = persistent)",
  },
  {
    id: 6,
    key: "closable",
    prop: "closable",
    type: "boolean",
    default: "true",
    description: "Whether to show close button",
  },
  {
    id: 7,
    key: "action",
    prop: "action",
    type: "ReactNode",
    default: "-",
    description: "Custom action buttons or elements",
  },
  {
    id: 8,
    key: "icon",
    prop: "icon",
    type: "ReactNode",
    default: "auto",
    description: "Custom icon or false to hide",
  },
  {
    id: 9,
    key: "position",
    prop: "position",
    type: "top | top-left | top-right | bottom | bottom-left |bottom-right",
    default: "top-right",
    description: "Screen position for the toast",
  },
  {
    id: 10,
    key: "size",
    prop: "size",
    type: "sm | md | lg",
    default: "md",
    description: "Size variant for the toast",
  },
  {
    id: 11,
    key: "variant",
    prop: "variant",
    type: "solid | bordered | flat | faded | shadow",
    default: "solid",
    description: "Visual style variant",
  },
  {
    id: 12,
    key: "radius",
    prop: "radius",
    type: "none | sm | md | lg | full",
    default: "md",
    description: "Border radius size",
  },
  {
    id: 13,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes",
  },
  {
    id: 14,
    key: "onClose",
    prop: "onClose",
    type: "(id: string) => void",
    default: "-",
    description: "Callback when toast is closed",
  },
  {
    id: 15,
    key: "onRemove",
    prop: "onRemove",
    type: "(id: string) => void",
    default: "-",
    description: "Function to remove the toast",
  },
  {
    id: 16,
    key: "data-testid",
    prop: "data-testid",
    type: "string",
    default: "-",
    description: "Test identifier attribute",
  },
  {
    id: 17,
    key: "color",
    prop: "color",
    type: "success | error | warning | info | default",
    default: "primary",
    description: "Custom color theme for the toast",
  },
];

// ToastProviderProps columns and content
export const toastProviderPropsColumns = [
  { key: "prop", label: "PROP", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "default", label: "DEFAULT", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const toastProviderPropsContent = [
  {
    id: 1,
    key: "children",
    prop: "children",
    type: "ReactNode",
    default: "-",
    description: "Application content to wrap",
  },
  {
    id: 2,
    key: "position",
    prop: "position",
    type: "ToastPosition",
    default: '"top-right"',
    description: "Default position for all toasts",
  },
  {
    id: 3,
    key: "maxToasts",
    prop: "maxToasts",
    type: "number",
    default: "5",
    description: "Maximum number of toasts to show",
  },
  {
    id: 4,
    key: "defaultDuration",
    prop: "defaultDuration",
    type: "number",
    default: "4000",
    description: "Default auto-dismiss duration",
  },
  {
    id: 5,
    key: "className",
    prop: "className",
    type: "string",
    default: "-",
    description: "Additional CSS classes for container",
  },
];

// UseToastReturn columns and content
export const useToastReturnColumns = [
  { key: "method", label: "METHOD", allowsSorting: false },
  { key: "type", label: "TYPE", allowsSorting: false },
  { key: "description", label: "DESCRIPTION", allowsSorting: false },
];

export const useToastReturnContent = [
  {
    id: 1,
    key: "toast",
    method: "toast",
    type: "(message: string, options?: ToastOptions) => string",
    description: "Show a default toast",
  },
  {
    id: 2,
    key: "success",
    method: "success",
    type: "(message: string, options?) => string",
    description: "Show a success toast",
  },
  {
    id: 3,
    key: "error",
    method: "error",
    type: "(message: string, options?) => string",
    description: "Show an error toast",
  },
  {
    id: 4,
    key: "warning",
    method: "warning",
    type: "(message: string, options?) => string",
    description: "Show a warning toast",
  },
  {
    id: 5,
    key: "info",
    method: "info",
    type: "(message: string, options?) => string",
    description: "Show an info toast",
  },
  {
    id: 6,
    key: "dismiss",
    method: "dismiss",
    type: "(id: string) => void",
    description: "Dismiss a specific toast",
  },
  {
    id: 7,
    key: "dismissAll",
    method: "dismissAll",
    type: "() => void",
    description: "Dismiss all active toasts",
  },
  {
    id: 8,
    key: "update",
    method: "update",
    type: "(id: string, updates: Partial<ToastItem>) => void",
    description: "Update an existing toast",
  },
];
