import { tv } from 'tailwind-variants';

export const navbar = tv({
  slots: {
    base: [
      'flex',
      'z-40',
      'w-full',
      'h-auto',
      'items-center',
      'justify-between',
      'transition-background',
      'duration-300',
      'ease-in-out',
      'data-[menu-open=true]:bg-content1/60',
      'data-[hidden=true]:transform',
      'data-[hidden=true]:-translate-y-full',
      'data-[hidden=true]:transition-transform',
    ],
    wrapper: [
      'z-40',
      'flex',
      'px-6',
      'gap-4',
      'w-full',
      'flex-row',
      'relative',
      'flex-nowrap',
      'items-center',
      'justify-between',
      'h-16',
    ],
    brand: ['flex', 'basis-0', 'flex-row', 'flex-grow', 'flex-nowrap'],
    content: [
      'flex',
      'gap-4',
      'h-full',
      'flex-row',
      'flex-nowrap',
      'items-center',
      'data-[justify=start]:justify-start',
      'data-[justify=start]:flex-grow',
      'data-[justify=center]:justify-center',
      'data-[justify=end]:justify-end',
      'data-[justify=end]:flex-grow',
      'data-[justify=end]:basis-0',
    ],
    item: [
      'text-medium',
      'whitespace-nowrap',
      'box-border',
      'list-none',
      'data-[active=true]:font-medium',
      'data-[active=true]:text-primary',
    ],
    toggle: [
      'group',
      'flex',
      'items-center',
      'justify-center',
      'w-6',
      'h-full',
      'outline-none',
      'rounded-small',
      'tap-highlight-transparent',
      'data-[pressed=true]:bg-default-100',
      'data-[hover=true]:bg-default-100',
      'data-[open=true]:bg-default-100',
    ],
    toggleIcon: [
      'w-full',
      'h-full',
      'pointer-events-none',
      'flex',
      'flex-col',
      'items-center',
      'justify-center',
      'text-inherit',
      'group-data-[pressed=true]:opacity-70',
      'transition-opacity',
      'before:content-[""]',
      'before:block',
      'before:h-px',
      'before:w-4',
      'before:bg-current',
      'before:transition-transform',
      'before:duration-150',
      'before:-translate-y-1',
      'before:rotate-0',
      'after:content-[""]',
      'after:block',
      'after:h-px',
      'after:w-4',
      'after:bg-current',
      'after:transition-transform',
      'after:duration-150',
      'after:translate-y-1',
      'after:rotate-0',
      'group-data-[open=true]:before:translate-y-px',
      'group-data-[open=true]:before:rotate-45',
      'group-data-[open=true]:after:-translate-y-px',
      'group-data-[open=true]:after:-rotate-45',
    ],
    menu: [
      'z-30',
      'px-6',
      'pt-2',
      'fixed',
      'flex',
      'max-w-full',
      'top-header',
      'inset-x-0',
      'bottom-0',
      'w-screen',
      'flex-col',
      'gap-2',
      'overflow-y-auto',
      'bg-content1/60',
      'backdrop-blur-xl',
      'backdrop-saturate-150',
    ],
    menuItem: [
      'text-large',
      'color-foreground',
      'data-[active=true]:font-semibold',
      'data-[active=true]:text-primary',
    ],
  },
  variants: {
    position: {
      static: {
        base: 'relative',
      },
      sticky: {
        base: 'sticky top-0',
      },
    },
    maxWidth: {
      sm: {
        wrapper: 'max-w-[640px]',
      },
      md: {
        wrapper: 'max-w-[768px]',
      },
      lg: {
        wrapper: 'max-w-[1024px]',
      },
      xl: {
        wrapper: 'max-w-[1280px]',
      },
      '2xl': {
        wrapper: 'max-w-[1536px]',
      },
      full: {
        wrapper: 'max-w-full',
      },
    },
    isBordered: {
      true: {
        base: 'border-b border-divider',
      },
    },
    isBlurred: {
      true: {
        base: [
          'backdrop-blur-lg',
          'data-[menu-open=false]:bg-background/70',
          'backdrop-saturate-150',
        ],
      },
      false: {
        base: 'bg-background',
        menu: 'bg-background',
      },
    },
    disableAnimation: {
      true: {
        menu: '!transition-none',
      },
    },
  },
  defaultVariants: {
    position: 'sticky',
    maxWidth: 'lg',
    isBordered: false,
    isBlurred: true,
    disableAnimation: false,
  },
});

export type NavbarVariantProps = Parameters<typeof navbar>[0];
export type NavbarSlots = keyof ReturnType<typeof navbar>;